name: Merge Request CI

on:
  push:
    branches: [slack-integration]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-lint:
    name: Test and Lint incoming Pull Requests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies using Yarn
        run: yarn install

      - name: Check for Linting Errors
        run: yarn lint

      - name: Execute Unit Tests
        run: yarn test

  slack-notification:
    name: Send Slack Notification for incoming Pull Requests
    runs-on: ubuntu-latest

    steps:
      - uses:
          - actions/checkout@v2
          - kceb/pull-request-url-action@v1
            id: pr-url

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: pull-requests
          SLACK_USERNAME: GitHub Bot
          SLACK_ICON_EMOJI: ':robot_face:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: New Pull Request Opened for the ${{ github.event.repository.name }} Repo. 
          SLACK_MESSAGE: ${{ steps.pr-url.outputs.url }}
          MSG_MINIMAL: true
